version: '3'
services:
  mqrabbit:
    image: rabbitmq:management
    restart: always
    deploy:
      placement:
        constraints:
           - node.role != manager
      replicas: 2
networks:
  default:
    external:
      name: Service04_network
