version: '3'

services:
  user_rpc:
    build: python/
    image: user_rpc
    restart: always
    depends_on:
      - db
    networks:
      - webproxy
      - default
    deploy:
     replicas: 2

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=devops101
      - MYSQL_DATABASE=devops_db
      - MYSQL_USER=devops
      - MYSQL_PASSWORD=devops101

networks:
  default:
    external:
      name: Service04_network
  webproxy:
    external:
      name: Revproxy04_network
