version: '3'

services:
  register:
    build: python/
    image: gateway_register
    restart: always
    ports:
      - "7001:80"
    deploy:
      replicas: 2

networks:
  default:
    external:
      name: Service04_network
